# Generated by Django 5.1.4 on 2024-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(
                default="Пока ничего не рассказал о себе", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="Не указано", max_length=70),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
