# Generated by Django 5.1.4 on 2024-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_about_alter_user_avatar_alter_user_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="createdAt",
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(
                blank=True, default="Пока ничего не рассказал о себе", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default="Не указано", max_length=70),
        ),
    ]
