# Generated by Django 5.1.4 on 2024-12-18 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_createdat_alter_user_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="createdAt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
