# Generated by Django 5.1.4 on 2024-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(
                blank=True,
                default="Пока ничего не рассказал о себе",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default="Не указано", max_length=70, null=True
            ),
        ),
    ]
