# Generated by Django 5.1.4 on 2024-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_about_alter_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, default="Город не указан", max_length=70, null=True
            ),
        ),
    ]
