# Generated by Django 5.1.4 on 2024-12-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="createdAt",
        ),
    ]
