# Generated by Django 5.1.4 on 2024-12-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="replies",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_replies",
                to="comments.comment",
            ),
        ),
    ]
