# Generated by Django 5.1.4 on 2024-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_alter_comment_createdat"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
