# Generated by Django 5.1.4 on 2024-12-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_comment_is_edited_alter_comment_createdat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_edited",
        ),
    ]
