# Generated by Django 5.1.4 on 2024-12-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_remove_comment_is_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
