# Generated by Django 5.1.4 on 2024-12-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_comment_is_edited"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
