# Generated by Django 5.1.4 on 2024-12-12 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=70,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=70,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("image", models.URLField()),
                ("text", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
