# Generated by Django 5.1.4 on 2024-12-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="Posts",
        ),
    ]
