# Generated by Django 5.1.4 on 2024-12-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-createdAt"]},
        ),
    ]
