# Generated by Django 5.1.4 on 2024-12-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_post_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
